# Generated by Django 4.2.8 on 2023-12-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../icons8-person-female-100_q2xckn', upload_to='images/'),
        ),
    ]
