# Generated by Django 4.2.8 on 2023-12-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_owner',
            new_name='owner',
        ),
    ]
