# Generated by Django 4.2.8 on 2023-12-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
