# Generated by Django 4.2.8 on 2023-12-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
