# Generated by Django 4.2.8 on 2023-12-21 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='receipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
