# Generated by Django 4.2.8 on 2023-12-23 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='buyer',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='offer',
            name='initial_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
