# Generated by Django 4.2.8 on 2023-12-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_rename_buyer_offer_owner_offer_initial_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='owner',
            new_name='buyer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='initial_buyer',
        ),
    ]
