# Generated by Django 4.2.8 on 2023-12-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_receipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='receipient',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='receiver',
            new_name='seller',
        ),
    ]
