# Generated by Django 4.2.8 on 2023-12-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_receipient_offer_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='seller',
        ),
    ]
