# Generated by Django 4.2.8 on 2023-12-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_owner_offer_buyer_remove_offer_initial_buyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
    ]
