# Generated by Django 4.2.8 on 2024-01-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='message',
        ),
    ]
