# Generated by Django 4.2.8 on 2023-12-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
