# Generated by Django 4.2.8 on 2023-12-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_advert_options_remove_advert_hit_count_generic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='advert_owner',
            new_name='owner',
        ),
    ]
