# Generated by Django 4.2.8 on 2023-12-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_advert_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='payment_options',
            field=models.CharField(choices=[('cash', 'Cash only'), ('PayPal', 'PayPal only'), ('EITHER', 'Cash or Paypal')], default='EITHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='advert',
            name='shippment_options',
            field=models.CharField(choices=[('collection', 'Collection Only'), ('postage', 'Royal Mail Only'), ('EITHER', 'Collection or Royal Mail delivery')], default='EITHER', max_length=50),
        ),
    ]
