# Generated by Django 4.2.8 on 2024-01-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_alter_advert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
