# Generated by Django 4.2.8 on 2024-01-21 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_advert_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='contact_dets',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
