# Generated by Django 4.2.8 on 2023-12-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_rename_owner_advert_advert_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='advert_owner',
            new_name='owner',
        ),
    ]
