# Generated by Django 4.2.8 on 2024-01-22 23:04

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('adverts', '0006_alter_advert_item_description_alter_advert_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='item_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advert',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
