# Generated by Django 4.2.8 on 2023-12-16 20:07

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('adverts', '0007_alter_advert_advert_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='advert',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
